name: symfony-telegram-notifier

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    networks:
      - internal
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=symfonyTelegramNotifier"
    volumes:
      - ./.docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./bin:/var/www/bin:ro
      - ./config:/var/www/config:ro
      - ./public:/var/www/public:ro
      - ./src:/var/www/src:ro
      - ./tests:/var/www/tests:ro
      - ./var:/var/www/var
      - ./.env:/var/www/.env:ro
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./symfony.lock:/var/www/symfony.lock
      - ./phpstan.neon.dist:/var/www/phpstan.neon.dist:ro
      - ./phpunit.xml.dist:/var/www/phpunit.xml.dist:ro
      - ./rector.php:/var/www/rector.php:ro
    networks:
      - internal

networks:
  internal:
    driver: bridge
